baseURL: "https://blainefinstein.github.io" 
title: Blaine Finstein
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 1 
        - name: Papers
          url: papers/
          weight: 2
        - name: Data
          url: data/
          weight: 4 

params:
    description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Blaine Finstein
          subtitle: "Hi! My name is Blaine Finstein and I am a PhD student in political science at UCLA. My work focuses on the political economy of development, NGOs, and computational methods."
          imageUrl: "headshot copy.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Blaine Finstein
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Email
          url: mailto:moritz.maria.von.igelfeld@gmail.com
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://twitter.com/McCallSmith

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
